apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: httpd-arm
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: httpd-${NAME}
      env: ${ENVIRONMENT}
    name: httpd-${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: httpd-${NAME}
    template:
      metadata:
        labels:
          app: httpd-${NAME}
          env: ${ENVIRONMENT}
      spec:
        containers:
        - image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          name: httpd-${NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: httpd-${NAME}
      env: ${ENVIRONMENT}
    name: httpd-${NAME}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: httpd-${NAME}
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: httpd-${NAME}
      env: ${ENVIRONMENT}
    name: httpd-${NAME}
  spec:
    host: httpd-${NAME}-devops.apps-crc.testing
    port:
      targetPort: 8080
    to:
      kind: Service
      name: httpd-${NAME}
parameters:
  - name: NAME
    from: '[a-z]{5}'
    generate: expression
    description: Deployment name
    required: false
  - name: IMAGE
    value: quay.io/rh-ee-mtahmeed/httpd:arm
    description: default image name
    required: true
  - name: ENVIRONMENT
    description: provide meaning to deployment
    required: false
  - name: LABELS
    value: tahmeed
labels:
  abcd: ${LABELS}

