apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: demo-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: demo-trigger
      bindings:
        - ref: demo-binding
      template:
        ref: demo-template