apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: git-clone-and-push
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: git-url
    - name: git-revision
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared-workspace