apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: demo-binding
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.ref)
  workspace:
        - name: output
          workspace: shared