apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: wtops-binding
spec:
  params:
    - name: git-url
      value: $(body.repository.clone_url)
    - name: git-revision
      value: $(body.ref)